export const endpoints = {
  auth: {
    login: "/auth/login",
    registerClient: "/auth/register/client",
    registerManager: "/auth/register/manager",
    verifyOtp: "/auth/verify-otp",
    resendOtp: "/auth/resend-otp",
    refresh: "/auth/refresh-token",
    logout: "/auth/logout",
    logoutAll: "/auth/logout-all",
    sessions: "/auth/sessions",
    changePassword: "/auth/change-password",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    verifyResetOtp: "/auth/verify-reset-otp",
    mfaValidate: "/auth/mfa/validate",
    google: "/auth/google",
  },
  users: {
    me: "/users/me",
    avatar: "/users/me/avatar",
  },
  admin: "/admin",
  provider: "/provider",
  client: "/client",
  chat: "/chat",
  notifications: "/notifications",
  services: "/services",
  bookings: "/bookings",
  vehicles: "/vehicles",
  discover: "/discover",
  diagnosticReports: "/diagnostic_reports",
  reportFindings: "/report_findings",
  recommendedRepairs: "/recommended_repairs",
  loyaltyConfig: "/loyalty_config",
};
